### ISSUE TITLE
e r r o r 

### ISSUE THREAD

**Issue by AnksioXD** [ragxxv/Bumpr#1]
is it still working dud? i cant get it to work, [literally just changed the ids and prefix](https://gist.github.com/AnksioXD/6e5e0d05ce682dc12fbe03090badc5ee).

heres an error:

Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x7f62fa4dc9c0>>
#### Traceback (most recent call last):
  File "/home/runner/frek/venv/lib/python3.10/site-packages/discum/gateway/gateway.py", line 303, in _response_loop
    function(resp, **params)
  File "main.py", line 21, in bump
    data = s.get(['bump'])
  File "/home/runner/frek/venv/lib/python3.10/site-packages/discum/utils/slash.py", line 84, in get
    current_cmd = next(
  File "/home/runner/frek/venv/lib/python3.10/site-packages/discum/utils/slash.py", line 87, in <genexpr>
    if c["name"] == cmd and c["type"] in (1, 2)
KeyError: 'name'

**Comment by AnksioXD** [comment]
got it working nvm
